# Generated by Django 3.2.15 on 2022-08-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorSearches',
            fields=[
                ('author_key', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=128)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BookSearches',
            fields=[
                ('key', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
